spring:
  application: 
    name: healthcare/local  
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/patientmodule
    username: ${username}
    password: ${password}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
data: local data 11
